### PR TITLE
Initial Commit to add Kotlin SDK

### LINKED ISSUE #70: [SDK Request] Java SDK
Related Roadmap issue: https://github.com/openfga/roadmap/issues/5
Related Discussion: https://github.com/orgs/openfga/discussions/31

### PR DESCRIPTION
**Pull request by rorychatterton**
## Description
- [x] Enable Kotlin SDK Generation for OpenFGA.
- [ ] Create Openfga.dev Maven Namespace for publishing
- [ ] Move generated Kotlin Client to openfga from https://github.com/rorychatterton/fga-kotlin-sdk to https://github.com/openfga/kotlin-sdk
- [ ] Update Readme Templates
- [ ] Update Github Actions to publish tagged version to Maven

## References

- closes #70 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by adriantam** [comment]
Hello @rorychatterton , thank you for contributing!
Can you confirm whether this PR is ready for review?  All the template files are empty.  If you need more time, feel free to mark this as "Draft" (i.e., Convert to draft) until it is ready for review.  If you need help, feel free to let us know!

**Comment by rorychatterton** [comment]
Whoops. I thought I had raised this as a draft PR to mark that it was in progress.

Marking as Draft.

**Comment by rhamzeh** [comment]
Thanks for the PR @rorychatterton! And for the link, we'll work on creating the namespace and adding the secrets as well as adding the Snyk and FOSSA checks early next week.

In the meantime, I hope you don't mind us providing a bit of feedback to ensure consistency with the other SDKs:
- [ ] Consistent configuration. Having the same configuration interface as the rest of the SDKs makes it easier for users to switch between them
- [ ] Consistent API method calls
- [ ] Tests. While more tests in general is always a good thing, when this is ready, can you make sure at least the base tests are met? You can take a look at the existing tests for [Go](https://github.com/openfga/sdk-generator/blob/main/config/clients/go/template/fga_test.mustache), [JS](https://github.com/openfga/sdk-generator/blob/main/config/clients/js/template/tests/index.test.ts.mustache), .NET [API](https://github.com/openfga/sdk-generator/blob/main/config/clients/dotnet/template/api_test.mustache) and [Models](https://github.com/openfga/sdk-generator/blob/main/config/clients/dotnet/template/models_test.mustache) and Python [API](https://github.com/openfga/sdk-generator/blob/main/config/clients/python/template/api_test.mustache) and [Credentials](https://github.com/openfga/sdk-generator/blob/main/config/clients/python/template/credentials_test.mustache)
- [ ] Support for No Credentials, Credentials with a Bearer Token, and Client Credentials flow (Client Credentials flow can be added post v0.0.1)
- [ ] Minimal non-dev dependencies

**Comment by rorychatterton** [comment]
Thanks @rhamzeh. I likely won't get back around to this until late next week so no rush on the namespace/secrets.

| Consistent configuration. Having the same configuration interface as the rest of the SDKs makes it easier for users to switch between them

I'll need to have a think about how to approach this one. In web apps in Java, it's normal to have the properies fetched from your Application.properties file - of which you can then redirect the contents of THAT file to env variables. 

In the current implementation, the ApiHost is automatically fetched from the application.properties file in the generated client base. [The Host Key Location](https://github.com/Ozee-io/fga-kotlin-sdk/blob/main/src/main/kotlin/dev/openfga/kotlin/client/infrastructure/ApiClient.kt#L47) and [Where it is fetched](https://github.com/Ozee-io/fga-kotlin-sdk/blob/main/src/main/kotlin/dev/openfga/kotlin/client/apis/OpenFgaApi.kt#L70). 

I think overriding this default functionality, as the developer would just need to redirect the new call to the same properties rotation. I suspect we are better off sticking to the Java convention as that is what happens in other libraries today. 

Re: StoreID, The API Generator makes this an argument to all of the CRUD functions in the API Class, as so:

```kotlin
// Get StoreID from Properties
@Value("\${dev.openfga.kotlin.client.storeId}")
lateinit var storeId: String

// Create an instance of the API
private val api: OpenFgaApi = OpenFgaApi()

val response = api.readAuthorizationModels(
    storeId=storeId,
)
```

I'm not sure there's an easy way for me to change that behaviour to be part of the base OpenfgaApi class without overriding all of the endpoints with mustache. I'm not super confident in doing that. 

Do you have a better idea?

| Support for No Credentials, Credentials with a Bearer Token, and Client Credentials flow (Client Credentials flow can be added post v0.0.1)

Got it

|  Consistent API method calls

From what I can tell, all the method endpoints are pretty much identical to the Python Library (where I first played with Openfga) - there should be nothing to do here. 

| Tests. While more tests in general is always a good thing, when this is ready, can you make sure at least the base tests are met? You can take a look at the existing tests.

Yep, I'll do my best. 

| Minimal non-dev dependencies

The only dependencies in the current api is the ones generated by swagger, and the maven-publish plugin. I have added no additional dependencies.

I have stuck with the default libraries of the [swagger kotlin generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/kotlin.md), as they appear to be hte most cross-compatible for kotlin + java users. i.e:
- jvm-okhttp4
- dateLibrary: Java8
- keeping the coroutines library disabled (as I believe that becomes a bit more complex for Java vs Kotlin cross compatibility, although am happy to be corrected there)

**Comment by rorychatterton** [comment]
Sorry, I will be closing this PR for the time being. 

In the application we are developing, we landed on using a Graph Database as the backend for the service. At its current scale, it is easier to model permissions in the database than call out to a separate service. 

We will likely pick this up again in 6 months once we require an independent RBAC microservice. 

Sorry for the false alarm.

**Comment by rhamzeh** [comment]
Thanks for your update on this @rorychatterton! Best of luck with your chosen service. In many use-cases, that would be the right approach.

If you get back to evaluating OpenFGA in a couple of months, hopefully we'll have had the Java/Kotlin SDK out by then.

Thanks for giving OpenFGA a try!

**Pull request closed without merging**
