### PR TITLE
fix(go-sdk): validate correct credentials method config

### PR DESCRIPTION
**Pull request by matt-potter**
## Description
Fix validation of config in go-sdk. Validation func is applying client_credentials validation to api_token cred method.

## Review Checklist
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by rhamzeh** [comment]
Thanks for noticing this and for your contribution @matt-potter!

**Review by rhamzeh — DISMISSED** [review]

**Comment by rhamzeh** [comment]
@matt-potter Can I ask you to add a test case [here](https://github.com/openfga/sdk-generator/blob/main/config/clients/go/template/fga_test.mustache#L64)

It should look something like the one for [ClientCredentials](https://github.com/openfga/sdk-generator/blob/main/config/clients/go/template/fga_test.mustache#L163)

**Comment by matt-potter** [comment]
> @matt-potter Can I ask you to add a test case [here](https://github.com/openfga/sdk-generator/blob/main/config/clients/go/template/fga_test.mustache#L64)

Sure, no problem!

**Comment by matt-potter** [comment]
I've added a test, @rhamzeh

**Review by rhamzeh — APPROVED** [review]
Confirming that the test is failing before the fix in this PR, and succeeds after.

This PR is cleared for merging, thanks for your contribution @matt-potter! 🎉

**Note**: GitHub actions do not seem to be running.

While we investigate, to unblock this PR, they have all been run locally with no issues encountered.
- [x] Test Client Generator
- [x] Test JS SDK
- [x] Test Go SDK
- [x] Test .NET SDK

**Comment by rhamzeh** [comment]
Thanks for your contribution @matt-potter and apologies for the delay in getting this out. v0.0.3 has your fix!

**Pull request merged**
