### PR TITLE
docs: Use invite link for Discord Server in README

### PR DESCRIPTION
**Pull request by booniepepper**
## Description

The previous link only works for folks who are already part of the server. This link should work for anyone, and put them in the `#fga-general` channel.

## References

Discord discussion: https://discord.com/channels/759188666072825867/930524706854031421/1133095840676859934

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [ ] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by rhamzeh** [comment]
Thanks @booniepepper -  can I ask you to also update: https://github.com/openfga/sdk-generator/blob/main/config/common/files/README.mustache#L6 to use `{{discordUrl}}` from the common config (https://github.com/openfga/sdk-generator/blob/main/config/common/config.base.json#L25C4-L25C14)?

**Review by rhamzeh — CHANGES_REQUESTED** [review]
Thanks @booniepepper -  can I ask you to also update: https://github.com/openfga/sdk-generator/blob/main/config/common/files/README.mustache#L6 to use `{{discordUrl}}` from the common config (https://github.com/openfga/sdk-generator/blob/main/config/common/config.base.json#L25C4-L25C14)?

**Comment by booniepepper** [comment]
Will do!

**Comment by booniepepper** [comment]
Hmm, I'm not sure if I can pass some of the tests right now. (Open to ideas! I might be missing something) This account won't have access to credentials, but I can't create a new branch for this repository

**Comment by booniepepper** [comment]
Will open as a new PR from a different branch

**Pull request closed without merging**
